name: Publish to npm
author: pascalgn
description: Automatically publish new versions to npm

inputs:
  create_tag:
    description: The boolean that creating tag
    required: false
  commit_pattern:
    description: The pattern that matches version update commits.
    required: false
  tag_name:
    description: The name of the tag that you want to create for the version.
    required: false
  tag_message:
    description: The message of the tag that you want to create for the version.
    required: false
  workspace:
    description: Custom workspace directory that contains the package.json file.
    required: false
  publish_command:
    description: Custom publish command.
    required: false
  publish_args:
    description: Publish command arguments.
    required: false
  build_command:
    description: Build command
    required: false

runs:
  using: docker
  image: Dockerfile

branding:
  icon: package
  color: blue
